"""source usage monthly counter

Revision ID: 3b789237a599
Revises: 8b30d0284a57
Create Date: 2026-07-07 02:50:35.356253
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3b789237a599'
down_revision: Union[str, None] = '8b30d0284a57'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('source_usage',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('service', sa.String(length=40), nullable=False),
    sa.Column('month', sa.String(length=7), nullable=False),
    sa.Column('calls', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('service', 'month', name='uq_source_usage_service_month')
    )
    with op.batch_alter_table('source_usage', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_source_usage_service'), ['service'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('source_usage', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_source_usage_service'))

    op.drop_table('source_usage')
    # ### end Alembic commands ###
