"""llm usage monthly counter

Revision ID: 8b30d0284a57
Revises: a05ec687c07b
Create Date: 2026-07-06 17:11:46.905527
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8b30d0284a57'
down_revision: Union[str, None] = 'a05ec687c07b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('llm_usage',
    sa.Column('month', sa.String(length=7), nullable=False),
    sa.Column('calls', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('month')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('llm_usage')
    # ### end Alembic commands ###
