"""resume grade_json

Revision ID: 108eeeb69f68
Revises: b592d88ea103
Create Date: 2026-07-07 07:34:35.880702
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '108eeeb69f68'
down_revision: Union[str, None] = 'b592d88ea103'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('preferences', schema=None) as batch_op:
        batch_op.alter_column('exclude_staffing',
               existing_type=sa.BOOLEAN(),
               nullable=False)

    with op.batch_alter_table('resumes', schema=None) as batch_op:
        batch_op.add_column(sa.Column('grade_json', sa.JSON(), nullable=True))

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('resumes', schema=None) as batch_op:
        batch_op.drop_column('grade_json')

    with op.batch_alter_table('preferences', schema=None) as batch_op:
        batch_op.alter_column('exclude_staffing',
               existing_type=sa.BOOLEAN(),
               nullable=True)

    # ### end Alembic commands ###
