"""pref must-have, block companies, exclude staffing

Revision ID: b592d88ea103
Revises: 4b6eed939a1a
Create Date: 2026-07-07 06:15:46.497065
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b592d88ea103'
down_revision: Union[str, None] = '4b6eed939a1a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('preferences', schema=None) as batch_op:
        batch_op.add_column(sa.Column('must_have_keywords', sa.JSON(), nullable=True))
        batch_op.add_column(sa.Column('block_companies', sa.JSON(), nullable=True))
        batch_op.add_column(sa.Column('exclude_staffing', sa.Boolean(), nullable=False))

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('preferences', schema=None) as batch_op:
        batch_op.drop_column('exclude_staffing')
        batch_op.drop_column('block_companies')
        batch_op.drop_column('must_have_keywords')

    # ### end Alembic commands ###
