"""ats ingestion: companies table + job ats fields

Revision ID: fe47f9bc2b38
Revises: 0c1580f734a0
Create Date: 2026-06-28 04:40:58.609698
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'fe47f9bc2b38'
down_revision: Union[str, None] = '0c1580f734a0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('companies',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('ats_provider', sa.String(length=20), nullable=False),
    sa.Column('ats_id', sa.String(length=120), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('ats_provider', 'ats_id', name='uq_company_ats')
    )
    with op.batch_alter_table('jobs', schema=None) as batch_op:
        batch_op.add_column(sa.Column('company_id', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('remote_type', sa.String(length=20), nullable=True))
        batch_op.add_column(sa.Column('salary_min', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('salary_max', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('salary_currency', sa.String(length=8), nullable=True))
        batch_op.add_column(sa.Column('description_md', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('posted_at', sa.DateTime(timezone=True), nullable=True))
        batch_op.add_column(sa.Column('ghost_score', sa.Float(), nullable=True))
        batch_op.create_index(batch_op.f('ix_jobs_company_id'), ['company_id'], unique=False)
        batch_op.create_foreign_key(
            'fk_jobs_company_id', 'companies', ['company_id'], ['id'], ondelete='SET NULL'
        )

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('jobs', schema=None) as batch_op:
        batch_op.drop_constraint('fk_jobs_company_id', type_='foreignkey')
        batch_op.drop_index(batch_op.f('ix_jobs_company_id'))
        batch_op.drop_column('ghost_score')
        batch_op.drop_column('posted_at')
        batch_op.drop_column('description_md')
        batch_op.drop_column('salary_currency')
        batch_op.drop_column('salary_max')
        batch_op.drop_column('salary_min')
        batch_op.drop_column('remote_type')
        batch_op.drop_column('company_id')

    op.drop_table('companies')
    # ### end Alembic commands ###
