"""star outcome from inbox watcher

Revision ID: 5e25af1c2de0
Revises: f1c8d62a9b47
Create Date: 2026-07-10 02:58:18.113445
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5e25af1c2de0'
down_revision: Union[str, None] = 'f1c8d62a9b47'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('stars', schema=None) as batch_op:
        batch_op.add_column(sa.Column('outcome', sa.String(length=20), nullable=True))

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('stars', schema=None) as batch_op:
        batch_op.drop_column('outcome')

    # ### end Alembic commands ###
