"""resume parsing: resumes.parsed_json

Revision ID: 96d70bea0c1a
Revises: fe47f9bc2b38
Create Date: 2026-06-28 05:13:47.095273
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '96d70bea0c1a'
down_revision: Union[str, None] = 'fe47f9bc2b38'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('resumes', schema=None) as batch_op:
        batch_op.add_column(sa.Column('parsed_json', sa.JSON(), nullable=True))

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('resumes', schema=None) as batch_op:
        batch_op.drop_column('parsed_json')

    # ### end Alembic commands ###
