"""add preference.exclude_keywords

Revision ID: 0c1580f734a0
Revises: c3e5f7a9d124
Create Date: 2026-06-28 03:33:46.134021
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0c1580f734a0'
down_revision: Union[str, None] = 'c3e5f7a9d124'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('preferences', schema=None) as batch_op:
        batch_op.add_column(sa.Column('exclude_keywords', sa.JSON(), nullable=True))

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('preferences', schema=None) as batch_op:
        batch_op.drop_column('exclude_keywords')

    # ### end Alembic commands ###
