"""application kits

Revision ID: ac99aa1e88aa
Revises: 108eeeb69f68
Create Date: 2026-07-07 17:39:16.700816
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ac99aa1e88aa'
down_revision: Union[str, None] = '108eeeb69f68'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('application_kits',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('job_id', sa.Integer(), nullable=False),
    sa.Column('content', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['job_id'], ['jobs.id'], name='fk_kit_job', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name='fk_kit_user', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'job_id', name='uq_kit_user_job')
    )
    with op.batch_alter_table('application_kits', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_application_kits_job_id'), ['job_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_application_kits_user_id'), ['user_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('application_kits', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_application_kits_user_id'))
        batch_op.drop_index(batch_op.f('ix_application_kits_job_id'))

    op.drop_table('application_kits')
    # ### end Alembic commands ###
