"""telegram chat, followup stamp

Revision ID: e9e034cb5133
Revises: ac99aa1e88aa
Create Date: 2026-07-07 17:59:32.891066
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e9e034cb5133'
down_revision: Union[str, None] = 'ac99aa1e88aa'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('stars', schema=None) as batch_op:
        batch_op.add_column(sa.Column('followup_at', sa.DateTime(timezone=True), nullable=True))

    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('telegram_chat_id', sa.String(length=32), nullable=True))
        batch_op.add_column(sa.Column('telegram_link_token', sa.String(length=64), nullable=True))

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('telegram_link_token')
        batch_op.drop_column('telegram_chat_id')

    with op.batch_alter_table('stars', schema=None) as batch_op:
        batch_op.drop_column('followup_at')

    # ### end Alembic commands ###
