"""match reason + llm score cache

Revision ID: a05ec687c07b
Revises: b7d2a4c9e1f0
Create Date: 2026-07-06 17:03:00.732075
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a05ec687c07b'
down_revision: Union[str, None] = 'b7d2a4c9e1f0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('llm_scores',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('job_id', sa.Integer(), nullable=False),
    sa.Column('resume_hash', sa.String(length=64), nullable=False),
    sa.Column('job_hash', sa.String(length=64), nullable=False),
    sa.Column('score', sa.Float(), nullable=False),
    sa.Column('reason', sa.Text(), nullable=False),
    sa.Column('model', sa.String(length=80), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['job_id'], ['jobs.id'], name='fk_llmscore_job', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('resume_hash', 'job_id', name='uq_llmscore_resume_job')
    )
    with op.batch_alter_table('llm_scores', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_llm_scores_job_id'), ['job_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_llm_scores_resume_hash'), ['resume_hash'], unique=False)

    with op.batch_alter_table('matches', schema=None) as batch_op:
        batch_op.add_column(sa.Column('reason', sa.Text(), nullable=True))

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('matches', schema=None) as batch_op:
        batch_op.drop_column('reason')

    with op.batch_alter_table('llm_scores', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_llm_scores_resume_hash'))
        batch_op.drop_index(batch_op.f('ix_llm_scores_job_id'))

    op.drop_table('llm_scores')
    # ### end Alembic commands ###
