"""initial schema

Revision ID: e8f382f0b960
Revises: 
Create Date: 2026-06-19 02:35:02.836247
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e8f382f0b960'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('jobs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('source', sa.String(length=40), nullable=False),
    sa.Column('external_id', sa.String(length=255), nullable=True),
    sa.Column('title', sa.String(length=300), nullable=False),
    sa.Column('company', sa.String(length=255), nullable=True),
    sa.Column('country', sa.String(length=60), nullable=True),
    sa.Column('location', sa.String(length=255), nullable=True),
    sa.Column('work_type', sa.String(length=20), nullable=True),
    sa.Column('salary', sa.Integer(), nullable=True),
    sa.Column('posted_date', sa.Date(), nullable=True),
    sa.Column('url', sa.String(length=1000), nullable=True),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('fetched_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('dedupe_key', sa.String(length=500), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('source', 'external_id', name='uq_source_external_id')
    )
    with op.batch_alter_table('jobs', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_jobs_dedupe_key'), ['dedupe_key'], unique=False)
        batch_op.create_index(batch_op.f('ix_jobs_posted_date'), ['posted_date'], unique=False)
        batch_op.create_index(batch_op.f('ix_jobs_source'), ['source'], unique=False)

    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=320), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('role', sa.String(length=20), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_users_email'), ['email'], unique=True)

    op.create_table('application_answers',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('job_id', sa.Integer(), nullable=False),
    sa.Column('question', sa.Text(), nullable=False),
    sa.Column('draft_answer', sa.Text(), nullable=False),
    sa.Column('final_answer', sa.Text(), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['job_id'], ['jobs.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('application_answers', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_application_answers_job_id'), ['job_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_application_answers_user_id'), ['user_id'], unique=False)

    op.create_table('matches',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('job_id', sa.Integer(), nullable=False),
    sa.Column('score', sa.Float(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('notified_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['job_id'], ['jobs.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'job_id', name='uq_user_job_match')
    )
    with op.batch_alter_table('matches', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_matches_job_id'), ['job_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_matches_user_id'), ['user_id'], unique=False)

    op.create_table('preferences',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('country', sa.String(length=60), nullable=True),
    sa.Column('city', sa.String(length=120), nullable=True),
    sa.Column('radius_miles', sa.Integer(), nullable=True),
    sa.Column('work_types', sa.JSON(), nullable=True),
    sa.Column('posted_within_days', sa.Integer(), nullable=True),
    sa.Column('keywords', sa.JSON(), nullable=True),
    sa.Column('salary_min', sa.Integer(), nullable=True),
    sa.Column('employment_type', sa.String(length=40), nullable=True),
    sa.Column('seniority', sa.String(length=40), nullable=True),
    sa.Column('match_threshold', sa.Integer(), nullable=False),
    sa.Column('alert_channels', sa.JSON(), nullable=True),
    sa.Column('digest_mode', sa.String(length=20), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('user_id')
    )
    op.create_table('resumes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('kind', sa.String(length=20), nullable=False),
    sa.Column('filename', sa.String(length=255), nullable=False),
    sa.Column('raw_text', sa.Text(), nullable=False),
    sa.Column('uploaded_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('resumes', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_resumes_user_id'), ['user_id'], unique=False)

    op.create_table('stars',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('job_id', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['job_id'], ['jobs.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'job_id', name='uq_user_job_star')
    )
    with op.batch_alter_table('stars', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_stars_job_id'), ['job_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_stars_user_id'), ['user_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('stars', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_stars_user_id'))
        batch_op.drop_index(batch_op.f('ix_stars_job_id'))

    op.drop_table('stars')
    with op.batch_alter_table('resumes', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_resumes_user_id'))

    op.drop_table('resumes')
    op.drop_table('preferences')
    with op.batch_alter_table('matches', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_matches_user_id'))
        batch_op.drop_index(batch_op.f('ix_matches_job_id'))

    op.drop_table('matches')
    with op.batch_alter_table('application_answers', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_application_answers_user_id'))
        batch_op.drop_index(batch_op.f('ix_application_answers_job_id'))

    op.drop_table('application_answers')
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_users_email'))

    op.drop_table('users')
    with op.batch_alter_table('jobs', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_jobs_source'))
        batch_op.drop_index(batch_op.f('ix_jobs_posted_date'))
        batch_op.drop_index(batch_op.f('ix_jobs_dedupe_key'))

    op.drop_table('jobs')
    # ### end Alembic commands ###
